### ISSUE TITLE
AI search UI/UX modification

### ISSUE THREAD

**Issue by elv-haoyu** [eluv-io/elv-ai-search#1]
1. Adjust the widths of the search index and search input boxes. The search input box should be wider than the search index box to better accommodate longer query terms and improve usability. <img width="1297" alt="image" src="https://github.com/user-attachments/assets/c4b8b72c-9c36-477b-8af6-faf7d8617a80">

2. Please ensure that only non-empty tag tracks are displayed. The `shot detection` and `shot tags` tracks should be excluded, as the former represents the start and end times of the clip, and the latter is the aggregated result of all other tracks. <img width="1293" alt="image" src="https://github.com/user-attachments/assets/d7fe2e56-3213-41f5-84ed-eb66d622c025">

3. Add a `Generate Summary` button that triggers the summary API when clicked @elv-joe.

**Comment by elv-joe** [comment]
I put up a design punch list at [here](https://docs.google.com/document/d/1PxaxbFLHDgHwhfiZgrcFIktEDSEn0blh_xlcw0SUEUc/edit)

1.
    - The first part of the search bar should be where the search input text go 
    - There should have a dropdown arrow followed by the placeholder/search input text which allows user to select the search index
    - "Clip icon + Search by image, video, or audio" is a button
    - When click the "search by other source" button will have a modal pop up for user to search by other sources

3. Will add!

**Comment by elv-zenia** [comment]
@elv-joe I'm not sure this loading state makes sense when generating hashtags. These skeleton views only make sense when the API returns X amount of results, then the app makes calls for each to get more data.

But for the summary api, the app has no idea how many results are getting returned until the response comes in, in which case, we can just show the normal view. The highlights API(s) are TBD so I can't speak to that.
![image](https://github.com/user-attachments/assets/f75ba13d-7b46-408c-970d-bdd4b4b21c0e)

**Comment by elv-zenia** [comment]
@elv-joe Would you add a way for the user to select a start and end time for the clip for the Create Summary page? To my understanding, the summarize api cannot create a summary for the full-length video.
https://www.figma.com/design/MkBARe4Ld0iSEhChDdeDhq/Video-Editor-App?node-id=673-81856&m=dev

**Comment by elv-joe** [comment]
1. Hashtag - We can take the skeleton off from the hashtags, just keep the loading circle
2. Highlight - if it turns out that we can't use the skeleton for highlight, we can always use the loading circle instead
![image](https://github.com/user-attachments/assets/8615932e-1b3f-4b77-9d42-06e9c96e3956)

3. Clip start and end time - will add!

**Comment by elv-haoyu** [comment]
All fixed/added.
