### ISSUE TITLE
Add manual index input in advanced settings

### ISSUE THREAD

**Issue by elv-joeA** [eluv-io/elv-ai-search#14]
In addition to allowing the user to choose indexes that are pre-defined on the tenant object, we would also like to add back the ability to input an index IQ (under "Advanced Settings".   This will probably need a text field and a "Use Index" button which loads the manually inputted index IQ.

**Comment by elv-joeA** [comment]
If the user has input a custom index, then all the radio buttons should be unselected, and advanced settings should be pre-opened when selecting the index triangle, so it's obvious that you're using a custom index.

**Comment by elv-zenia** [comment]
This is deployed to prod
