### ISSUE TITLE
Crossing out on the Tags button clears out the entire screen.

### ISSUE THREAD

**Issue by elv-Sauptik** [eluv-io/elv-ai-search#3]
After search and clicking on a result. If we click on the x button far right next to tags the screen goes all blank. Attaching screenshots.

Click on x
![Screenshot 2024-09-05 at 1 33 58 PM](https://github.com/user-attachments/assets/4b1a4980-28c5-4bf5-9a43-70b82c952294)

Screen goes blank
![Screenshot 2024-09-05 at 1 34 14 PM](https://github.com/user-attachments/assets/aa637751-6c6f-45ce-833a-2d7f3385abda)

**Comment by elv-zenia** [comment]
@elv-Sauptik deployed an update for this. Would you mind verifying it works now? You might need to do a hard reload in the browser.

**Comment by elv-Sauptik** [comment]
Thank you @elv-zenia . Works great! Closing the issue.
